[project]
name = "stock-trading-platform"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "hypothesis>=6.151.6",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]
